import argparse
import sys
import os
from datetime import datetime
from colorama import Fore, Style, init

# Initialise colorama for coloured terminal output
init(autoreset=True)

# Import our modules
from crawler import crawl
from modules import sqli, xss

# ─────────────────────────────────────────
#  BANNER
# ─────────────────────────────────────────

def print_banner():
    print(Fore.CYAN + """
╔══════════════════════════════════════════════╗
║         Web Vulnerability Scanner           ║
║         Built by: Ash (Ryugai-grey)         ║
║         github.com/Ryugai-grey              ║
╚══════════════════════════════════════════════╝
""" + Style.RESET_ALL)


# ─────────────────────────────────────────
#  REPORT GENERATOR
# ─────────────────────────────────────────

def generate_report(target, all_findings):
    """
    Takes all findings and writes a professional
    Markdown pentest report to the /reports folder.
    """

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"reports/scan-{timestamp}.md"

    # Count by severity
    critical = [f for f in all_findings if f["severity"] == "CRITICAL"]
    high     = [f for f in all_findings if f["severity"] == "HIGH"]
    medium   = [f for f in all_findings if f["severity"] == "MEDIUM"]

    with open(filename, "w", encoding="utf-8") as report:

        # Header
        report.write(f"# Web Vulnerability Scan Report\n\n")
        report.write(f"**Target:** {target}\n")
        report.write(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        report.write(f"**Scanner:** Web Vulnerability Scanner v1.0\n")
        report.write(f"**Author:** Ash (Ryugai-grey)\n\n")
        report.write("---\n\n")

        # Executive Summary
        report.write("## Executive Summary\n\n")
        report.write(f"A total of **{len(all_findings)} vulnerabilities** were identified:\n\n")
        report.write(f"| Severity | Count |\n")
        report.write(f"|----------|-------|\n")
        report.write(f"| 🔴 Critical | {len(critical)} |\n")
        report.write(f"| 🟠 High | {len(high)} |\n")
        report.write(f"| 🟡 Medium | {len(medium)} |\n\n")
        report.write("---\n\n")

        # Findings
        report.write("## Detailed Findings\n\n")

        if not all_findings:
            report.write("No vulnerabilities were detected during this scan.\n\n")
        else:
            for i, finding in enumerate(all_findings, 1):
                severity_icon = "🔴" if finding["severity"] == "CRITICAL" else "🟠"
                report.write(f"### Finding {i} — {finding['type']}\n\n")
                report.write(f"| Field | Detail |\n")
                report.write(f"|-------|--------|\n")
                report.write(f"| Severity | {severity_icon} {finding['severity']} |\n")
                report.write(f"| URL | `{finding['url']}` |\n")
                report.write(f"| Method | `{finding['method']}` |\n")
                report.write(f"| Fields Tested | `{finding['field']}` |\n")
                report.write(f"| OWASP Category | {finding['owasp']} |\n\n")

                report.write(f"**Payload that triggered it:**\n")
                report.write(f"```\n{finding['payload']}\n```\n\n")

                report.write(f"**Evidence:** {finding['evidence']}\n\n")

                report.write(f"**Remediation:**\n")
                report.write(f"> {finding['fix']}\n\n")
                report.write("---\n\n")

        # OWASP Reference
        report.write("## OWASP Top 10 Coverage\n\n")
        report.write("| OWASP ID | Category | Tested |\n")
        report.write("|----------|----------|--------|\n")
        report.write("| A03:2021 | Injection (SQLi) | ✅ |\n")
        report.write("| A03:2021 | Injection (XSS) | ✅ |\n")
        report.write("| A05:2021 | Security Misconfiguration | ✅ |\n\n")

        # Footer
        report.write("---\n\n")
        report.write("*Report generated by Web Vulnerability Scanner v1.0*\n")
        report.write("*For educational purposes only — only test systems you own or have permission to test.*\n")

    return filename


# ─────────────────────────────────────────
#  MAIN SCANNER ENGINE
# ─────────────────────────────────────────

def run_scan(target):

    print_banner()

    print(Fore.YELLOW + f"[*] Target: {target}")
    print(Fore.YELLOW + f"[*] Scan started: {datetime.now().strftime('%H:%M:%S')}\n")

    # ── Step 1: Crawl the target ──
    print(Fore.CYAN + "[PHASE 1] Crawling target...")
    forms = crawl(target)

    if not forms:
        print(Fore.RED + "[!] No forms found on target. Nothing to test.")
        sys.exit(1)

    print(Fore.GREEN + f"[+] Discovered {len(forms)} form(s) — proceeding to attack phase\n")

    # ── Step 2: Run attack modules ──
    print(Fore.CYAN + "[PHASE 2] Running vulnerability modules...\n")

    all_findings = []

    # SQL Injection
    sqli_findings = sqli.run(forms)
    all_findings.extend(sqli_findings)
    print()

    # XSS
    xss_findings = xss.run(forms)
    all_findings.extend(xss_findings)
    print()

    # ── Step 3: Print summary ──
    print(Fore.CYAN + "=" * 50)
    print(Fore.CYAN + "  SCAN COMPLETE")
    print(Fore.CYAN + "=" * 50)

    if all_findings:
        print(Fore.RED + f"\n  Total vulnerabilities found: {len(all_findings)}")
        for f in all_findings:
            colour = Fore.RED if f["severity"] == "CRITICAL" else Fore.YELLOW
            print(colour + f"  [{f['severity']}] {f['type']} — {f['url']}")
    else:
        print(Fore.GREEN + "\n  No vulnerabilities detected.")

    print()

    # ── Step 4: Generate report ──
    print(Fore.CYAN + "[PHASE 3] Generating report...")
    os.makedirs("reports", exist_ok=True)
    report_file = generate_report(target, all_findings)
    print(Fore.GREEN + f"[+] Report saved: {report_file}\n")


# ─────────────────────────────────────────
#  ENTRY POINT
# ─────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Web Vulnerability Scanner — SQLi & XSS detection"
    )
    parser.add_argument(
        "--target",
        required=True,
        help="Target URL to scan (e.g. http://127.0.0.1:5000)"
    )
    args = parser.parse_args()

    # Clean up the URL
    target = args.target.strip()
    if not target.startswith("http"):
        target = "http://" + target

    run_scan(target)